services:
  app:
    container_name: dockerrized_nestjs_container
    depends_on:
      app_mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
      # - .:/app                # Liên kết mã nguồn từ máy chủ vào container
      # - /app/node_modules     # Tránh ghi đè thư mục node_modules trong container
    command: "npm run start:dev" # Chạy ứng dụng ở chế độ dev
    networks:
      - nestjs_app_network

  app_mysql:
    image: mysql:8.0.39
    container_name: app_mysql_container
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    networks:
      - nestjs_app_network
    volumes:
      - root_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.0 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 3

  app_phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: app_phpmyadmin_container
    restart: unless-stopped
    depends_on:
      app_mysql:
        condition: service_healthy
    ports:
      - "8844:80"
    environment:
      PMA_HOST: app_mysql
      PMA_PORT: 3306
      PMA_PASSWORD: password
    networks:
      - nestjs_app_network

volumes:
  root_mysql_data:
    driver: local

networks:
  nestjs_app_network:
    driver: bridge
